- name: Install Dependencies
        run: npm install

      # This runs the "build" script from your package.json 
      # which creates the 'dist' folder and copies index.html into it
      - name: Build Web Assets
        run: npm run build

      - name: Capacitor Sync
        run: npx cap sync android

      - name: Grant execute permission for gradlew
        run: chmod +x android/gradlew

      - name: Build with Gradle
        run: cd android && ./gradlew assembleDebug
